language: java
sudo: false
jdk:
- oraclejdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_a63a9d7f8ae7_key -iv $encrypted_a63a9d7f8ae7_iv -in gradle.properties.enc -out gradle.properties -d
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/67add3390223c819bbe8
    on_success: change
    on_failure: always
    on_start: never
